spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: nelon
    password: nelon
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    payment-url: http://localhost:8060/api/v1/payments
    product-url: http://localhost:8050/api/v1/products